spring.application.name=projetomercado
#CRIE NA RAIZ DO TEU PROJETO um arquivo chamado .env
#   tudo que estiver entre ${} ÃÂ© o nome da variavel que deverÃÂ¡ ter no .env
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.type=trace

## NÃÂO MODIFICAR ISSO
spring.devtools.livereload.enabled=false
spring.devtools.restart.trigger-file=.reloadTriggerIfRestartIsFalse

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MT_USERNAME}
spring.mail.password=${MT_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
email.sender.from=nao-responda@projeto-mercado.dedyn.io

# "Interruptor" para ligar/desligar o envio de e-mail de confirmacao
email.confirmation.enabled=false

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH2_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH2_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.google.scope=email, profile
app.auth.oauth2.authorizedRedirectUris=http://localhost:5173/oauth2/redirect


server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false